# Generated by Django 6.0.6 on 2026-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='summary_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
