# Generated by Django 6.0.6 on 2026-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_pdfdocument_summary_pdfdocument_summary_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='index_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
